W4ExeStart-war/src/fit5042/tutex/controllers/PropertyController.java
package fit5042.tutex.controllers;

import javax.el.ELContext;
import javax.inject.Named;
import javax.enterprise.context.Dependent;
import javax.enterprise.context.RequestScoped;
import javax.faces.context.FacesContext;

/**
 *
 * @author Messom
 * @author Guan
 */
@Named(value = "propertyController")
@RequestScoped
public class PropertyController {

    private int propertyId; //this propertyId is the index, don't confuse with the Property Id

    public int getPropertyId() {
        return propertyId;
    }

    public void setPropertyId(int propertyId) {
        this.propertyId = propertyId;
    }
    private fit5042.tutex.repository.entities.Property property;

    public PropertyController() {
        // Assign property identifier via GET param 
        //this propertyID is the index, don't confuse with the Property Id
        propertyId = Integer.valueOf(FacesContext.getCurrentInstance()
                .getExternalContext()
                .getRequestParameterMap()
                .get("propertyID"));
        // Assign property based on the id provided 
        property = getProperty();
    }

    public fit5042.tutex.repository.entities.Property getProperty() {
        if (property == null) {
            // Get application context bean PropertyApplication 
            ELContext context
                    = FacesContext.getCurrentInstance().getELContext();
            PropertyApplication app
                    = (PropertyApplication) FacesContext.getCurrentInstance()
                            .getApplication()
                            .getELResolver()
                            .getValue(context, null, "propertyApplication");
            // -1 to propertyId since we +1 in JSF (to always have positive property id!) 
            return app.getProperties().get(--propertyId); //this propertyId is the index, don't confuse with the Property Id
        }
        return property;
    }
}

W4ExeStart-war/src/fit5042/tutex/controllers/TitleController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fit5042.tutex.controllers;

import javax.inject.Named;
import javax.enterprise.context.RequestScoped;
import javax.faces.context.FacesContext;

/**
 *
 * @author Guan
 */
@Named(value = "titleController")
@RequestScoped
public class TitleController {

    private String pageTitle;

    public TitleController() {
        // Set the page title 
        pageTitle = "Monash Real Estate Agency";
    }

    public String getPageTitle() {
        return pageTitle;
    }

    public void setPageTitle(String pageTitle) {
        this.pageTitle = pageTitle;
    }
}

W4ExeStart-war/src/fit5042/tutex/mbeans/PropertyManagedBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 */
package fit5042.tutex.mbeans;

import fit5042.tutex.repository.PropertyRepository;
import fit5042.tutex.repository.entities.Address;
import fit5042.tutex.repository.entities.ContactPerson;
import fit5042.tutex.repository.entities.Property;
import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import java.io.Serializable;
import java.util.List;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;

/**
 *
 * @author messomc
 * @author guan
 */
@ManagedBean(name = "propertyManagedBean")
@SessionScoped

public class PropertyManagedBean implements Serializable {

    @EJB
    PropertyRepository propertyRepository;

    /**
     * Creates a new instance of PropertyManagedBean
     */
    public PropertyManagedBean() {
    }

    public List<Property> getAllProperties() {
        try {
            List<Property> properties = propertyRepository.getAllProperties();
            return properties;
        } catch (Exception ex) {
            Logger.getLogger(PropertyManagedBean.class.getName()).log(Level.SEVERE, null, ex);
        }
        return null;
    }

    public void addProperty(Property property) {
        try {
            propertyRepository.addProperty(property);
        } catch (Exception ex) {
            Logger.getLogger(PropertyManagedBean.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * Search a property by Id
     */
    public Property searchPropertyById(int id) {
        try {
            return propertyRepository.searchPropertyById(id);
        } catch (Exception ex) {
            Logger.getLogger(PropertyManagedBean.class.getName()).log(Level.SEVERE, null, ex);
        }

        return null;
    }

    public Set<Property> searchPropertyByContactPerson(ContactPerson contactPerson) {
        try {
            return propertyRepository.searchPropertyByContactPerson(contactPerson);
        } catch (Exception ex) {
            Logger.getLogger(PropertyManagedBean.class.getName()).log(Level.SEVERE, null, ex);
        }

        return null;
    }

    public List<ContactPerson> getAllContactPeople() throws Exception {
        try {
            return propertyRepository.getAllContactPeople();
        } catch (Exception ex) {
            Logger.getLogger(PropertyManagedBean.class.getName()).log(Level.SEVERE, null, ex);
        }

        return null;
    }

    public void removeProperty(int propertyId) {
        try {
            propertyRepository.removeProperty(propertyId);
        } catch (Exception ex) {
            Logger.getLogger(PropertyManagedBean.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void editProperty(Property property) {
        try {
            String s = property.getAddress().getStreetNumber();
            Address address = property.getAddress();
            int c = property.getContactPerson().getConactPersonId();
            ContactPerson contactPerson = propertyRepository.findContactPersonById(c);
            property.setAddress(address);
            property.setContactPerson(contactPerson);

            propertyRepository.editProperty(property);

            FacesContext.getCurrentInstance().addMessage(null, new FacesMessage("Property has been updated succesfully"));
        } catch (Exception ex) {
            Logger.getLogger(PropertyManagedBean.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public List<Property> searchPropertyByBudget(double budget) {
        try {
            return propertyRepository.searchPropertyByBudget(budget);
        } catch (Exception ex) {
            Logger.getLogger(PropertyManagedBean.class.getName()).log(Level.SEVERE, null, ex);
        }

        return null;
    }

    public void addProperty(fit5042.tutex.controllers.Property localProperty) {
        //convert this newProperty which is the local property to entity property
        Property property = convertPropertyToEntity(localProperty);

        try {
            propertyRepository.addProperty(property);
        } catch (Exception ex) {
            Logger.getLogger(PropertyManagedBean.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private Property convertPropertyToEntity(fit5042.tutex.controllers.Property localProperty) {
        Property property = new Property(); //entity
        String streetNumber = localProperty.getStreetNumber();
        String streetAddress = localProperty.getStreetAddress();
        String suburb = localProperty.getSuburb();
        String postcode = localProperty.getPostcode();
        String state = localProperty.getState();
        Address address = new Address(streetNumber, streetAddress, suburb, postcode, state);
        property.setAddress(address);
        property.setNumberOfBedrooms(localProperty.getNumberOfBedrooms());
        property.setPrice(localProperty.getPrice());
        property.setSize(localProperty.getSize());
        property.setPropertyId(localProperty.getPropertyId());
        property.setTags(localProperty.getTags());
        int conactPersonId = localProperty.getConactPersonId();
        String name = localProperty.getName();
        String phoneNumber = localProperty.getPhoneNumber();
        ContactPerson contactPerson = new fit5042.tutex.repository.entities.ContactPerson(conactPersonId, name, phoneNumber);
        if (contactPerson.getConactPersonId() == 0) {
            contactPerson = null;
        }
        property.setContactPerson(contactPerson);
        return property;
    }

}

W4ExeStart-war/WebContent/add.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <h:outputStylesheet library="css" name="bootstrap.min.css"></h:outputStylesheet>
        <title>#{titleController.pageTitle}</title>
    </h:head>
    <h:body>
        <div class="container">
            <div class="navbar navbar-inverse">
                <div class="navbar-brand">
                    #{titleController.pageTitle} - Add Property
                </div>
            </div>
            <div>
        <f:view>
            <h:form>
                <h1><h:outputText value="Create"/></h1>
                <table class="table table-bordered ">

                    <tr>
                        <td width ="200">
                            <h:outputLabel value="streetNumber" for="streetNumber" />
                        </td>
                        <td>
                            <h:inputText id="streetNumber" value="#{property.streetNumber}" title="streetNumber" />
                        </td>

                    </tr>

                    <tr>
                        <td>
                            <h:outputLabel value="streetAddress" for="streetAddress" />
                        </td>
                        <td>
                            <h:inputText id="streetAddress" value="#{property.streetAddress}" title="streetAddress" />
                        </td>

                    </tr>

                    <tr>
                        <td>
                            <h:outputLabel value="suburb" for="suburb" />
                        </td>
                        <td>
                            <h:inputText id="suburb" value="#{property.suburb}" title="suburb" />
                        </td>

                    </tr>

                    <tr>
                        <td>
                            <h:outputLabel value="state" for="state" />
                        </td>
                        <td>
                            <h:inputText id="state" value="#{property.state}" title="state" />
                        </td>

                    </tr>
                    <tr>
                        <td>
                            <h:outputLabel value="postcode" for="postcode" />
                        </td>
                        <td>
                            <h:inputText id="postcode" value="#{property.postcode}" title="postcode" />
                        </td>

                    </tr>
                    <tr>
                        <td>
                            <h:outputLabel value="Size:" for="size" />
                        </td>
                        <td>
                            <h:inputText id="size" value="#{property.size}" title="Size" />
                        </td>

                    </tr>

                    <tr>
                        <td>
                            <h:outputLabel value="NumberOfBedrooms:" for="numberOfBedrooms" />
                        </td>
                        <td>
                            <h:inputText id="numberOfBedrooms" value="#{property.numberOfBedrooms}" title="NumberOfBedrooms" />
                        </td>

                    </tr>

                    <tr>
                        <td>
                            <h:outputLabel value="Price:" for="price" />
                        </td>
                        <td>
                            <h:inputText id="price" value="#{property.price}" title="Price" />
                        </td>

                    </tr>

                </table>

                <h:commandButton id="submit" value="Submit" action="#{addProperty.addProperty(property)}" class="btn btn-primary" />
                <h:link id="close" value="Close" outcome="faces/index.xhtml"
						          class="btn btn-primary" />

            </h:form>

        </f:view>
            </div>
        </div>

    </h:body>
</html>

W4ExeStart-war/WebContent/detail.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
    <h:head>
        <h:outputStylesheet library="css" name="bootstrap.min.css"></h:outputStylesheet>
        <title>#{titleController.pageTitle}</title>
    </h:head>
    <h:body>
        <div class="container">
            <div class="navbar navbar-inverse">
                <div class="navbar-brand">
                    #{titleController.pageTitle} - Edit Property
                </div>
            </div>

            <h:form id="MyForm">
                <table class="table table-bordered ">
                    <tr>
                        <td width ="150" valign="top">Id:</td>

                        <td valign="bottom">
                            <h:outputLabel id = "Id" >#{propertyController.property.propertyId}</h:outputLabel>
                        </td>
                    </tr>
                     <tr>
                        <td width ="100" valign="top">Address:</td>

                        <td valign="bottom">
                            <h:outputLabel id = "Address" >#{propertyController.property.address}</h:outputLabel>
                        </td>
                    </tr>
                    <tr>
                        <td width ="100" valign="top">No of Bedrooms: </td>

                        <td valign="bottom">
                            <h:outputLabel id = "No-Bedrooms" >#{propertyController.property.numberOfBedrooms}</h:outputLabel>
                        </td>
                    </tr>
                    <tr>
                        <td width ="100" valign="top">Price: </td>

                        <td valign="bottom">
                            <h:outputLabel id = "Price" >
                                #{propertyController.property.price}
                                 <f:convertNumber currencyCode="AUD" type="currency" />
                            </h:outputLabel>

                        </td>
                    </tr>
                    <tr>
                        <td width ="100" valign="top">Size: </td>

                        <td valign="bottom">
                            <h:outputLabel id = "Size" >#{propertyController.property.size}</h:outputLabel>
                        </td>
                    </tr>
                    <tr>
                        <td width ="100" valign="top">Contact Person: </td>

                        <td valign="bottom">
                            <h:outputLabel id = "ContactName" >#{propertyController.property.contactPerson.toString()}</h:outputLabel>
                        </td>
                    </tr>

                 </table>
                 <h:link id="close" value="Close" outcome="faces/index.xhtml"
 						          class="btn btn-primary" />

            </h:form>
        </div>
    </h:body>
</html>

W4ExeStart-war/WebContent/edit.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
    <h:head>
        <h:outputStylesheet library="css" name="bootstrap.min.css"></h:outputStylesheet>
        <title>#{titleController.pageTitle}</title>
    </h:head>
    <h:body>
        <div class="container">
            <div class="navbar navbar-inverse">
                <div class="navbar-brand">
                    #{titleController.pageTitle} - Property Details
                </div>
            </div>

            <h:form id="MyForm">
                <table class="table table-bordered ">

                    <tr>
                        <td width ="150" valign="top">Id:</td>

                        <td valign="bottom">
                            <h:outputLabel id = "Id" >#{propertyController.property.propertyId}</h:outputLabel>
                        </td>
                    </tr>
                    <tr>
                        <td width ="100" valign="top">Street number: </td>
                         
                        <td valign="bottom">
                            <h:inputText id = "streetNumber" value="#{propertyController.property.address.streetNumber}" binding="#{streetNumber}" required="true"
                                         validatorMessage="Please enter a valid street number."
                                         requiredMessage="Please enter an street number. "></h:inputText>
                        </td>
                    </tr>
                    <tr>
                        <td width ="100" valign="top">No of Bedrooms: </td>

                        <td valign="bottom">
                            <h:inputText id = "No-Bedrooms" value="#{propertyController.property.numberOfBedrooms}"  required="true"
                                         validatorMessage="Number of rooms must be greater than 0"
                                                 requiredMessage="Please enter number of rooms. "></h:inputText>
                        </td>
                    </tr>
                    <tr>
                        <td width ="100" valign="top">Price: </td>

                        <td valign="bottom">
                            <h:inputText id = "Price" value="#{propertyController.property.price}"  required="true"
                                         validatorMessage="Please enter a value greater than 0.0"
                                                 requiredMessage="Please enter a price. ">

                                 <f:convertNumber currencyCode="AUD" type="currency" />
                            </h:inputText>

                        </td>
                    </tr>
                    <tr>
                        <td width ="100" valign="top">Size: </td>

                        <td valign="bottom">
                            <h:inputText id = "Size" value="#{propertyController.property.size}"  required="true"
                                         validatorMessage="Please enter a value greater than 0.0"
                                                 requiredMessage="Please enter a size. "></h:inputText>
                        </td>
                    </tr>
                    <tr>
                    	<td width ="100" valign="top">Contact Person: </td>
                    	<td>
                    	<h:selectOneMenu id="contact" value="#{propertyController.property.contactPerson.conactPersonId}" >
                        	<f:selectItem itemValue="#{null}" itemLabel="--select--" />
                        	<f:selectItems value="#{propertyManagedBean.allContactPeople}" var="c"  
                                       itemLabel="#{c.name}" itemValue="#{c.conactPersonId}" />
                    	</h:selectOneMenu>
                    	</td>
                    </tr>

                </table>

                <h:commandButton id="save" value="Save" action="#{propertyManagedBean.editProperty(propertyController.property)}"  class="btn btn-primary" >
                    <f:param name="propertyID" value="#{propertyController.propertyId+1}"/>
                </h:commandButton>
                <h:link id="close" value="Close" outcome="faces/index.xhtml"
						          class="btn btn-primary" />
            </h:form>
        </div>
    </h:body>
</html>

W4ExeStart-war/WebContent/index.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://xmlns.jcp.org/jsf/passthrough">
    <h:head>
        <h:outputStylesheet library="css" name="bootstrap.min.css"></h:outputStylesheet>
        <title>#{titleController.pageTitle}</title>
    </h:head>
    <h:body>
        <div class="container">
            <div class="navbar navbar-inverse">
                <div class="navbar-brand">
                    #{titleController.pageTitle} - Property  List
                </div>
            </div>

            <h:form id="MyForm">
                <table class="table table-bordered table-striped">
                    <!-- For each property in properties ArrayList... -->
                    <tr>
                            <td>
                                <h:outputLabel id="Id" value="Id"  />
                            </td>
                            <td>
                                <h:outputLabel id="Price" value="Price"  />
                            </td>

                            <td>
                                <h:outputLabel id="Address" value="Address"/>
                            </td>

                     </tr>

                    <ui:repeat id="Myrepeat" value="#{propertyApplication.properties}"  var="property" varStatus="status">

                        <tr onclick="document.getElementById('MyForm:principle').value = document.getElementById('MyForm:Myrepeat:#{status.index}:outPrice').textContent">
                            <td>
                                <h:outputText value="#{propertyApplication.properties.get(status.index).propertyId}" id="propertyID" />

                            </td>

                            <td>
                                <h:outputText id="outPrice" value="#{propertyApplication.properties.get(status.index).price}"  />
                            </td>
                            <td>
                                <h:outputText id="outAddress" value="#{propertyApplication.properties.get(status.index).address}"></h:outputText>
                            </td>
                            <td>
                              <h:link value="View | " outcome="faces/detail.xhtml">
                              <!-- pass the parameter to next page, the param name is propertyID, and the value is index + 1.
                                You can get the value from next page using the indexController -->
                                <f:param name="propertyID" value="#{status.index + 1}"/>
                              </h:link>

                              <h:link value="Edit | " outcome="faces/edit.xhtml">
                              <!-- pass the parameter to next page, the param name is propertyID, and the value is index + 1.
                                You can get the value from next page using the indexController -->
                                <f:param name="propertyID" value="#{status.index + 1}"/>
                              </h:link>

                                <h:commandLink value="Delete" action="#{removeProperty.removeProperty(propertyApplication.properties.get(status.index).propertyId)}" disabled="#{propertyApplication.properties.get(status.index).propertyId == null}">
                                </h:commandLink>

                                <h:outputText value=" "/>
                            </td>

                        </tr>

                    </ui:repeat>

                </table>

                <div>
                    <h:commandButton id="add" value="Add" action="add.xhtml" class="btn btn-primary" />

                    <h:commandButton id="viewAll" value="View All" action="#{searchProperty.searchAll()}" class="btn btn-primary" >
                        <f:param name="propertyID" value="#{status.index + 1}"/>
                    </h:commandButton>
                </div>
                <div>
                    <h:inputText value="#{searchProperty.searchByInt}" id="searchById" required="true" onchange ="if (document.getElementById('MyForm:searchById').value.trim() == '') {document.getElementById('MyForm:searchById').value = 0;} "   />
                    <h:commandButton id="searchId" value="Search by Id" action="#{searchProperty.searchPropertyById(searchProperty.searchByInt)}" class="btn btn-primary" >
                        <f:param name="propertyID" value="#{status.index + 1}"/>
                    </h:commandButton>
                </div>
                <div>
                    <h:inputText value="#{searchProperty.searchByDouble}" id="searchByBudget" required="true" onchange="if (document.getElementById('MyForm:searchByBudget').value.trim() == '') {document.getElementById('MyForm:searchByBudget').value = 0.0;} " />
                    <h:commandButton id="searchBudget" value="Search by Budget" action="#{searchProperty.searchPropertyByBudget(searchProperty.searchByDouble)}" class="btn btn-primary" >
                        <f:param name="propertyID" value="#{status.index + 1}"/>
                    </h:commandButton>
                </div>


            </h:form>
        </div>
    </h:body>
</html>